### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by gabrielrobert** [hjeti/vue-generator#1]
```
$ npm install -g vue-generator
$ vg wizard
```

> let wizardType;
> ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3
> 

```
$ node -v
v4.4.5
```

```
$ npm -v
4.3.0
```

**Comment by hjeti** [comment]
Vue generator is build for node v6 or higher. Updating to node v6 will fix your issue. 

Official Node Long Term Support for node v4 ends april 2017 so now is a good time to update.

https://github.com/nodejs/LTS#lts-schedule
